import { createElement } from '@lwc/engine-dom';
import ProductSelectorWithScreenFlow from 'c/productSelectorWithScreenFlow';

describe('c-product-selector-with-screen-flow', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-product-selector-with-screen-flow', {
            is: ProductSelectorWithScreenFlow
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});